services:
  ai:
    build: ./ai
    expose: 
      - "7555"
  db:
    build: ./db
    expose: 
      - "7788"
  app:
    build: ./app
    ports: 
      - "9000:5555"
    links: 
      - "db"
      - "ai"
